/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed Sep 20 23:54:26 2017. */

#include "MessageProto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Head_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Head, code, code, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Head, msg, code, 0),
    PB_LAST_FIELD
};

const pb_field_t Body_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Body, count, count, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Body, content, count, 0),
    PB_LAST_FIELD
};

const pb_field_t Message_fields[12] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Message, int32Value, int32Value, 0),
    PB_FIELD(  2, INT32   , REPEATED, CALLBACK, OTHER, Message, int32ListValue, int32Value, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, Message, stringValue, int32ListValue, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, Message, stringValue128, stringValue, 0),
    PB_FIELD(  6, STRING  , REPEATED, CALLBACK, OTHER, Message, stringListValue, stringValue128, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, Message, floatValue, stringListValue, 0),
    PB_FIELD(  8, DOUBLE  , OPTIONAL, STATIC  , OTHER, Message, doubleValue, floatValue, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, Message, boolValue, doubleValue, 0),
    PB_FIELD( 10, UENUM   , OPTIONAL, STATIC  , OTHER, Message, status, boolValue, 0),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, Message, head, status, &Head_fields),
    PB_FIELD( 12, MESSAGE , REPEATED, CALLBACK, OTHER, Message, body, head, &Body_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, head) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Head_Body_Message)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, head) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Head_Body_Message)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
